{
 "title": "Мониторинг приложения",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RPS (запросов/сек)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_received_total[1m])",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Latency p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[1m]))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "HTTP 5xx rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_received_total{status=~\"5..\"}[1m])",
     "legendFormat": "5xx rate"
    }
   ]
  },
  {
   "title": "Логи Nginx",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{container=\"nginx\"}"
    }
   ]
  }
 ]
}