global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['web:80']   # метрики ASP.NET
    metrics_path: /metrics

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']